name: Create Release

on:
  push:
    branches:
      - 'release-*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java:
          - 11
        vault:
          - 1.12.11
          - 1.13.0
          - 1.13.1
          - 1.13.2
          - 1.13.3
          - 1.13.4
          - 1.13.5
          - 1.13.6
          - 1.13.7
          - 1.13.8
          - 1.14.0
          - 1.14.1
          - 1.14.2
          - 1.14.3
          - 1.14.4
          - 1.15.0
          - latest
        os:
          - ubuntu-latest
          - windows-latest
        include:
          # TODO(casz) remove once https://github.com/testcontainers/testcontainers-java/pull/1780 is available
          - os: 'ubuntu-latest'
            tasks: 'integrationTest'

    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/heads\/release-/}

      - uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            ${{ matrix.tasks }}
            -s
            --info
        env:
          VAULT_VERSION: ${{ matrix.vault }}

      ##
      #  Create a Github Release
      #
      - uses: ncipollo/release-action@v1
        with:
          body: Release version ${{ steps.get_tag_name.outputs.VERSION }}
          tag: ${{ steps.get_tag_name.outputs.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/libs/vault-java-driver-${{ steps.get_tag_name.outputs.VERSION }}.jar"